# Generated by Django 4.0.4 on 2022-05-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=555)),
                ('date', models.DateField()),
                ('progress', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
